env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
project_name: sqlboiler-pgx
release:
  github:
    owner: UnAfraid
    name: sqlboiler-pgx
  name_template: '{{.Tag}}'
builds:
  - id: release
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - release
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip
